### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by Rverkade** [GraniteDevices/SimpleMotionV2#1]
SimpleMotionV2 is not able to compile in Qt or any other IDE, please see attached image
![knipsel](https://cloud.githubusercontent.com/assets/11457704/6636850/479cc802-c974-11e4-860f-df025e1690e9.PNG)

**Comment by TeroK** [comment]
Sorry, didn't notice this issue in time. I hope you have found solution! Let me know if more help needed.
