### ISSUE TITLE
MSVC Compilation fails on devicedeployment.c:76

### ISSUE THREAD

**Issue by oskaritimperi** [GraniteDevices/SimpleMotionV2#11]
Passing a const variable as the array size is not supported in MSVC (or in C). The fix is to use a `#define` or an enum for the `maxLineLen` value. This feature is supported when compiling in C++ mode, but then there are other compilation problems.

This affects both master and develop branches.

**Comment by oskaritimperi** [comment]
@TeroK I can create a PR for this, but should I create it against master or develop?

**Comment by TeroK** [comment]
Thanks for reporting & fix proposal! I'll make the change to both develop and master branches.
