### ISSUE TITLE
Take travis & appveyor into use

### ISSUE THREAD

**Issue by oskaritimperi** [GraniteDevices/SimpleMotionV2#12]
There are free CI tools available for open source projects. These tools can be used to check that your code is compiling on multiple platforms and that there are no warnings generated. It also makes it unnecessary to have your own hardware and development tools for all of these platforms.

Popular choices are Travis CI for building on Linux and macOS and AppVeyor for building on Windows. Both services have good integration with GitHub.

Taking these services into use is not a big thing. Write some settings files, have some build scripts and start coding. You can see an example in my fork: https://github.com/oswjk/SimpleMotionV2/commits/travis

The example I posted above builds SimpleMotionV2 for Linux, macOS and Windows x86/x64, so four platforms are compiled on each commit.

What are you thoughts about this?

**Comment by oskaritimperi** [comment]
And just that I don't forget: there's also https://scan.coverity.com/ which provides free static analysis for opensource projects.

**Comment by TeroK** [comment]
Thanks for great idea and working example scripts! I'm setting up both Travis and AppVeyor.

**Comment by TeroK** [comment]
Both are now in place & working. Thanks! It was pretty easy with your help.
